default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: FiFiBlog_database

test:
  <<: *default
  database: FiFiBlog_database_test

production:
  <<: *default
  database: FiFiBlog_database_production